"""add concept explanation cache

Revision ID: 3bae62b19c1e
Revises: 009d7a87d7bc
Create Date: 2026-06-07 19:41:06.308835
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3bae62b19c1e'
down_revision: Union[str, None] = '009d7a87d7bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_explanation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trail_id', sa.Integer(), nullable=False),
    sa.Column('ticket_code', sa.String(length=20), nullable=False),
    sa.Column('concept_key', sa.String(length=200), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trail_id'], ['learning_trails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trail_id', 'ticket_code', 'concept_key', name='uq_concept_cache_trail_ticket_concept')
    )
    op.create_index(op.f('ix_concept_explanation_cache_trail_id'), 'concept_explanation_cache', ['trail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concept_explanation_cache_trail_id'), table_name='concept_explanation_cache')
    op.drop_table('concept_explanation_cache')
    # ### end Alembic commands ###
